FORMAT: 1A
HOST: https://api-test.alphymart.com/

# Alphy API V1
## What is Alphy API V1
Alphy provides a complete API accessible via HTTPS.

## Setup for REST API
For using this API you need send authenticated HTTP requests. Exists several 
way to do this:
* Send a HTTPS header with include 'Cookie' : `AlphyMartToken={api_token}` where `{api_token}` is your API token.
![name](https://i.postimg.cc/Prmkc7WG/Alphy_Mart_Token.jpg)

## Basic Usage
### HTTPS
* All endpoints are available over HTTPS only.

### Allowed HTTPs requests:
* `POST` - To create resource
* `PUT` - To update resource
* `GET` - Get a resource or list of resources
* `DELETE` - To delete resource

### Description Of Usual Server Responses:
* 200 `ok` - the request was successful
    * `ok` 
        * `true` mean success to process 
    * `status` - status of process
        * `SuccessQuery`
        * `SuccessInsert`
        * `SuccessDelete`
        * `SuccessUpdate`
        * `SuccessRequest`
        * `SuccessLogin`
        * `SuccessLogout`
        * `SuccessConfirmEmail`
    * `warning`
        * null
    * `error`
        * null
    * `data` - Json data response from Api
        * Object
    * `timestamp`
    
* 400 `Bad Request` - the request could not be understood or was missing required parameters.
    * `ok` 
        * `false` mean failed to process
    * `status` - status of process
    * `warning` - warning message return from server
    * `timestamp`

* 401 `Unauthorized` - authentication failed or user doesn't have 
permissions for requested operation.

* 500 `Internal server error` - server error

### Attributes
* Date: The standard is called ISO-8601 and the format is: `YYYY-MM-DDTHH:mm:ss.sssZ`
    * Example: `2018-08-08T08:08:08.000Z`.

## Group Retailer

### /v1/retailerAccount/getNatureOfBusinessList
#### GET
+ Get list of nature of business

+ Response 200 (application/json)

    + Body
    
            {
            "ok": true,
            "status": "SuccessQuery",
            "warning": null,
            "error": null,
            "data": [
            "BEAUTY CENTRE / HAIR SALON / COSMETICS",
            "BUILDING MAINTENANCE",
            "CHILD CARE / NURSING SERVICES",
            "DEPARTMENTAL STORE / SUPERMARKET / MINIMARKET",
            "ELECTRICAL INDUSTRY",
            "ELECTRONIC INDUSTRY",
            "ENTERTAINMENT",
            "FASHION / CLOTHING / TEXTILE INDUSTRY",
            "FISHING INDUSTRY",
            "FOOD AND BEVERAGE",
            "FURNITURE",
            "MEDICAL / HEALTHCARE",
            "METAL INDUSTRY",
            "MUSICAL INSTRUMENT",
            "PHARMACEUTICAL",
            "PHOTOGRAPHY / VIDEOGRAPHY",
            "PLASTIC PRODUCTS",
            "RETAIL / WHOLESALE",
            "RUBBER PRODUCTS",
            "SHOES / FOOTWEAR",
            "SPORTING GOODS / SPORTSWEAR",
            "TELECOMMUNICATIONS",
            "WOOD PRODUCTS",
            "OTHER"
            ],
            "timestamp": 1539159800
            }

### /v1/retailerAccount/login

#### POST

+ To login and get token.

+ Request

    + Headers
    
            Content-Type: application/json
        
    + Body
    
            {
                "email" : "",
                "password" : "",
                "rememberMe" : false
            }
        
+ Response 200 (application/json)

    + Headers
    
            Cookie: {AlphyMartToken=token}

    + Body
    
            {
                "ok": true,
                "status": "SuccessLogin",
                "warning": null,
                "error": null,
                "data": null,
                "timestamp": 1518081999
            }
        
### /v1/retailerAccount/logout

#### POST

+ Logout from the retailer account.

+ Request

    + Headers
    
            Cookie: {AlphyMartToken=token}
    
    + Body
    
            {
            
            }
    
+ Response 200 (application/json)

        {
             "ok": true,
            "status": "SuccessLogout",
            "warning": null,
            "error": null,
            "data": null,
            "timestamp": 1518083704
        }

### /v1/retailerAccount/CreateUser

#### POST
Register a new retailer account.

+ Request

    + Headers
        
            Accept: application/json
            AlphyMartToken: {token}
            
    + Body
    
            {
                "retailerAccountDTO": {
                "accountType":1,
                "email":"",
                "firstName":"",
                "lastName":"",
                "isMale":true,
                "contactNo":"",
                "dateTimeDOB":"",
                "nationality":"",
                "identityType":"1",
                "identityNumber":"",
                "CompanyInfoDTO":{
                   "CompanyName":"",
                   "CompanyRegistrationNumber":"",
                   "Address1":"",
                   "Address2":"",
                   "City":"",
                   "Postcode":"",
                   "State":"",
                   "Country":"",
                   "NatureOfBusiness":""
                  }
                },
                    "password": ""
            }

+ Response 200 (application/json)

        {
            OK
                
            + Body
        
                {
                    "ok": true,
                    "status": "SuccessInsert",
                    "warning": null,
                    "error": null,
                    "data": null,
                    "timestamp": 1517992916
                }
                    
        }